export default [
  {
    event: 'Open CIties',
    location: 'Centro Metropolitano de Diseño',
    date: 'Monday 24th September',
    date_es: 'Lunes 24 de septiembre',
    url: 'http://opencitiessummit.org/',
    invitation: false,
  },
  {
    event: 'Natural Resource Governance for All',
    location: 'Estacion Federal',
    date: 'Monday 24th September',
    date_es: 'Lunes 24 de septiembre',
    url: '',
    invitation: true,
  },
  {
    event: 'OD4D Network Summit',
    location: 'Facultad de Derecho',
    date: 'Monday 24th September',
    date_es: 'Lunes 24 de septiembre',
    url: 'http://od4d.net/',
    invitation: true,
  },
  {
    event: 'OAS Open Data GovCamp',
    location: 'Facultad de Derecho',
    date: 'Monday 24th September',
    date_es: 'Lunes 24 de septiembre',
    url: '',
    invitation: false,
  },
  {
    event: 'State of The Map',
    location: 'Centro Metropolitano de Diseño',
    date: 'Monday 24th & Tuesday 25th September',
    date_es: 'Lunes 24 y martes 25 de septiembre',
    url: 'https://state.osmlatam.org/',
    invitation: false,
  },
  {
    event: 'Open Heroines Summit - Gender Spotlight',
    location: 'Centro Metropolitano de Diseño',
    date: 'Tuesday 25th September',
    date_es: 'Martes 25 de septiembre',
    url: '',
    invitation: false,
  },
  {
    event: 'Open Data Research Symposium',
    location: 'Centro Cultural San Martín',
    date: 'Tuesday 25th September',
    date_es: 'Martes 25 de septiembre',
    url:
      'https://www.eventbrite.com/e/open-data-research-symposium-2018-tickets-47181009670',
    invitation: false,
  },
  {
    event: 'CKANCON 2018',
    location: 'Centro Cultural Recoleta',
    date: 'Tuesday 25th September',
    date_es: 'Martes 25 de septiembre',
    url: '',
    invitation: false,
  },
  {
    event: 'Open Contracting Workshop',
    location: 'Facultad de Derecho',
    date: 'Tuesday 25th September',
    date_es: 'Martes 25 de septiembre',
    url: '',
    invitation: false,
  },
  {
    event: 'Data Governance Forum',
    location: 'Facultad de Derecho',
    date: 'Tuesday 25th September',
    date_es: 'Martes 25 de septiembre',
    url: 'http://www.datagovernanceforum.com/',
    invitation: true,
  },
  {
    event: 'African Data Revolution',
    location: 'Facultad de Derecho',
    date: 'Tuesday 25th September',
    date_es: 'Martes 25 de septiembre',
    url: '',
    invitation: true,
  },
  {
    event: 'La Nación Data',
    location: 'La Nación',
    date: 'Tuesday 25th September',
    date_es: 'Martes 25 de septiembre',
    url: 'https://www.lanacion.com.ar/data',
    invitation: true,
  },
  {
    event: 'Open Data Leaders Summit',
    location: 'TBD',
    date: 'Tuesday 25th September',
    date_es: 'Martes 25 de septiembre',
    url: '',
    invitation: true,
  },
  {
    event: 'Open Data Charter',
    location: 'TBD',
    date: 'Tuesday 25th September',
    date_es: 'Martes 25 de septiembre',
    url: 'https://opendatacharter.net/',
    invitation: true,
  },
  {
    event: 'AbreLatam',
    location: 'Usina del Arte',
    date: 'Wednesday 26th September',
    date_es: 'Miércoles 26 de septiembre',
    url: 'http://2018.abrelatam.org/',
    invitation: false,
  },
  {
    event: 'Standards Day',
    location: 'Facultad de Derecho',
    date: 'Wednesday 26th September',
    date_es: 'Miércoles 26 de septiembre',
    url: '',
    invitation: false,
  },
  {
    event: 'NSO Side Event',
    location: 'Facultad de Derecho',
    date: 'Wednesday 26th September',
    date_es: 'Miércoles 26 de septiembre',
    url: '',
    invitation: true,
  },
]
